language: python
dist: trusty
sudo: false  # enable container-based build
branches:
  except:
    - gh-pages
install:
  - pip install tox
script:
  - tox
# workaround for https://github.com/travis-ci/travis-ci/issues/4794
os:
- linux
- osx
matrix:
    include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: "pypy"
      env: TOXENV=pypy
    allow_failures:
    - env: TOXENV=pypy
install:
- if [[ ! -z $TOXENV ]]; then pip install tox; fi
script:
- if [[ ! -z $TOXENV ]]; then tox -e $TOXENV; fi
